### ISSUE TITLE
Missing sdist on PyPI

### ISSUE THREAD

**Issue by mgorny** [ashvardanian/SimSIMD#113]
The package releases only binary wheels on PyPI but it's missing a source distribution. This makes it impossible to install it on platforms that aren't built as part of the cibuildwheel process, and it's a major hassle for Linux distributions that use sdist archives as source.

While at it, ideally please include tests in the archive.

**Comment by ashvardanian** [comment]
Hey @mgorny! Do you have any tips on how to do that?

**Comment by mgorny** [comment]
Thanks!
