### ISSUE TITLE
[Python] test_cosine repeatedly tests the same arguments

### ISSUE THREAD

**Issue by mgorny** [ashvardanian/SimSIMD#116]
https://github.com/ashvardanian/SimSIMD/blob/18d17686124ddebd9fe55eee56b2e0273a613d4b/python/test.py#L136-L147

Since the test is always seeded with the same value (of `0`), it means it is repeated 50 times with exactly the same values of `a` and `b`.

To confirm, if I add `raise ValueError(a)` there, I get:

```pytb
FAILED python/test.py::test_cosine[float64-11-1-50] - ValueError: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
FAILED python/test.py::test_cosine[float64-11-2-50] - ValueError: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
FAILED python/test.py::test_cosine[float64-11-3-50] - ValueError: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
FAILED python/test.py::test_cosine[float64-11-4-50] - ValueError: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
FAILED python/test.py::test_cosine[float64-11-5-50] - ValueError: [ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
...
```

Perhaps consider using [hypothesis](https://pypi.org/project/hypothesis/) instead, since it provides much better support for seeding and reproducing fuzzy tests.

**Comment by ashvardanian** [comment]
Thank you, @mgorny! Patching ;)
