### ISSUE TITLE
warning: ISO C does not support the ‘_Float16’ type

### ISSUE THREAD

**Issue by MarkReedZ** [ashvardanian/SimSIMD#122]
We have the following warnings.  I can replace _Float16 with simsimd_f16_t

```
/home/ch/code/mr/SimSIMD/include/simsimd/probability.h:485:35: warning: ISO C does not support the ‘_Float16’ type [-Wpedantic]
  485 |     __m512h one = _mm512_set1_ph((_Float16)1);
      |                                   ^~~~~~~~

```

**Comment by ashvardanian** [comment]
Yes, familiar with that. Do you know of a good way to avoid that warning?

**Comment by MarkReedZ** [comment]
simsimd_f16_t is _Float16 so I presume this PR is okay, but haven't tested it on sapphire yet.   Was there a reason we had to use _Float16 or was it just an oversight? 

https://github.com/ashvardanian/SimSIMD/pull/125

**Comment by ashvardanian** [comment]
I wanted to make it independent from the alias, and used `_Float16` similar to Intel docs.
