### ISSUE TITLE
Performance difference between other SIMD accelerator

### ISSUE THREAD

**Issue by pauldintel** [ashvardanian/SimSIMD#130]
Ash 
Any idea whether SimSIMD library can outperform acceleration comparing :  
https://github.com/jfalcou/eve

thanks

**Comment by ashvardanian** [comment]
I've never benchmarked Eve, but not sure if it's a fair comparison.

Both Eve and SimSIMD are SIMD accelerated and use similar underlying hardware capabilities (not sure if they handle SVE though), but the first is a larger C++ general purpose templates library, and the latter is a tiny C collection of mixed-precision numerical kernels tailored for Search.

Many years ago I went down the rabbit hole of designing something similar to Eve and failed. Now I prefer other approaches - either design a new compiler, or if ultimate performance is needed - write custom hardware-specific kernels for every operation (similar to SimSIMD & StringZilla, as well as Intel Hyperscan, simd-json, and simd-utf).
