### ISSUE TITLE
[python] Create an interface file

### ISSUE THREAD

**Issue by cbornet** [ashvardanian/SimSIMD#151]
It would be nice to have a `.pyi` integrated to the python package that would expose the types for IDEs auto-completion and type checkers.

**Comment by ashvardanian** [comment]
Agreed! Can you please contribute one, @cbornet?

**Comment by cbornet** [comment]
Why not. But I'm not a typing expert...

**Comment by ashvardanian** [comment]
Let's give it a try 🤗
