### ISSUE TITLE
Precision reduced between v4 and v5

### ISSUE THREAD

**Issue by cbornet** [ashvardanian/SimSIMD#153]
Is it expected ?
On my machine, the code
```python
import numpy as np
import simsimd as simd
X = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(simd.cosine(X, X))
```
prints `5.960464477539063e-08` on v4.4.0 and `0.00036910176277160645` on v5.0.0

**Comment by cbornet** [comment]
For me that was detected by a test in LangChain that uses `numpy.allclose()`

**Comment by ashvardanian** [comment]
Is it checked without passing atol/rtol arguments?

**Comment by cbornet** [comment]
Yes, with defaults.

**Comment by cbornet** [comment]
So do we have to accept the precision loss or will there be changes to improve it ?

**Comment by ashvardanian** [comment]
@cbornet can you please also share the output of this:

```bash
python -c "import simsimd; print(simsimd.get_capabilities())"
```

If it prints `haswell`, the issue is likely coming from [here](https://github.com/ashvardanian/SimSIMD/compare/v4.4.0...v5.0.0#diff-9a13357c179b50b64fa63c5253d2f70d87d85de6540a6fd8e14d550d4209f3daR1109-R1116) - the `rsqrt`. But I am not sure if it's a good idea to replace it with a more accurate solution. If so, we need to change it in every cosine distance kernel in `spatial.h`.

**Comment by cbornet** [comment]
Sure. Here is the result:
```bash
{'serial': True, 'neon': False, 'sve': False, 'neon_f16': False, 'sve_f16': False, 'neon_bf16': False, 'sve_bf16': False, 'neon_i8': False, 'sve_i8': False, 'haswell': True, 'skylake': False, 'ice': False, 'genoa': False, 'sapphire': False}
```
with the `haswell` on.

**Comment by ashvardanian** [comment]
That makes a lot of sense, thank you @cbornet!

**Comment by ashvardanian** [comment]
`matt_dz` suggested several [reading materials on Twitter](https://x.com/matt_dz/status/1823886143047491743):

- The CORE-MATH project. [link](https://core-math.gitlabpages.inria.fr/)
- Precision and Performance Analysis of C Standard Math Library Functions on GPUs. [link](https://dl.acm.org/doi/10.1145/3624062.3624166)
- Accuracy of Mathematical Functions in Single, Double, Double Extended, and Quadruple Precision [link](https://members.loria.fr/PZimmermann/papers/accuracy.pdf)
- Correctly-rounded evaluation of a function: why, how, and at what cost? [link](https://hal.science/hal-04474530/document)
- RLIBM: Rutgers Architecture and Programming Languages Lab's Correctly Rounded Libm [link](https://people.cs.rutgers.edu/~sn349/rlibm/)

I love that some of those materials explicitly target GPUs. I was thinking about putting together a mixed-precision math hackathon; all those links look like excellent preparation materials. Still, I must figure out when to allocate time for them properly. I've previously tried to mix such precision-calibration issues with other intra-day tasks, which was clearly not enough to grok them.

Help and recommendations are more than welcome!
