### ISSUE TITLE
Unsupported metric 'h' for two numpy matrices of type np.uint8?

### ISSUE THREAD

**Issue by stuartatnosible** [ashvardanian/SimSIMD#166]
Hi There,

I was just checking out version 5.1.0 and I noticed that this code no longer works:

```python
np.random.seed(42)

a_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))
b_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))

dist = np.array(simsimd.cdist(a_mat, b_mat, 'hamming'), dtype=np.uint8)
```

The error message that gets returned when I run the code is the following:

```python
ValueError: Unsupported metric 'h' and datatype combination ('B'/'B' and 'B'/'B')
```

When using versions 5.0.1, 5.0.0, and 4.4.0 the code works exactly as I would expect.

Ideally given the changes in 5.1.0 I was hoping to be able to rewrite the code like so:

```python
np.random.seed(42)

a_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))
b_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))

dist = np.array(simsimd.cdist(a_mat, b_mat, 'hamming', dtype="u8"))
```

To reduce the memory footprint when computing distances on very large matrices.

Am I missing something? My setup is Windows 11 + 13th Gen Intel(R) Core(TM) i7-13700HX.

Many Thanks,
Stuart Reid

**Comment by ashvardanian** [comment]
Nice catch! There is a problem with how NumPy propagates binary data to CPython. Does it work if you set dtype=“b8”?

PS: Sorry for inconvenience 🤗

**Comment by stuartatnosible** [comment]
No worries, SimSIMD is epic. The following code:

```python
np.random.seed(42)

a_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))
b_mat = np.ascontiguousarray(np.random.randint(0, 255, (100, 192), dtype=np.uint8))
dist = np.array(simsimd.cdist(a_mat, b_mat, metric="hamming", dtype="b8"))
```

Produces the same error using SimSIMD==5.1.0:

```python
ValueError: Unsupported metric 'h' and datatype combination ('B'/'B' and 'B'/'B')
```

I've tried a bunch of variations but I'm not winning.

**Comment by ashvardanian** [comment]
Can you please add this test at the end of test.py and I will submit a patch later today. Thanks!

**Comment by ashvardanian** [comment]
Thanks @stuartatnosible! I've added tests covering the described use-case and added documentation to `README.md`. Please let me know if you notice any other issues 🤗
