### ISSUE TITLE
Bug: README example rejected by mypy (incompatible type "ndarray[...]"; expected "memoryview")

### ISSUE THREAD

**Issue by pquentin** [ashvardanian/SimSIMD#171]
### Describe the bug

With SimSIMD 5.1.1, mypy reject the example from the README. SimSIMD 5.1.0 works fine.

### Steps to reproduce

Install numpy, SimSIMD and mypy:

```bash
pip install numpy simsimd mypy
```

Write to this file (straight from the README):

```python
import simsimd
import numpy as np

vec1 = np.random.randn(1536).astype(np.float32)
vec2 = np.random.randn(1536).astype(np.float32)
dist = simsimd.cosine(vec1, vec2)
```

Run mypy on that file:

```python
t.py:6: error: Argument 1 to "cosine" has incompatible type "ndarray[Any, dtype[floating[_32Bit]]]"; expected "memoryview"  [arg-type]
t.py:6: error: Argument 2 to "cosine" has incompatible type "ndarray[Any, dtype[floating[_32Bit]]]"; expected "memoryview"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

### Expected behavior

No error.

### SimSIMD version

5.1.1

### Operating System

Ubuntu, Fedora, macOS

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hey, @pquentin! Seems like when the .pyi file isn’t properly evaluated and we have to keep NumPy arrays as part of the union. Patching now 🤗
