### ISSUE TITLE
Bug: using value of assignment with ‘volatile’-qualified left operand is deprecated (GCC 13)

### ISSUE THREAD

**Issue by mbautin** [ashvardanian/SimSIMD#191]
### Describe the bug

Getting this error when trying to build with GCC 13

```
../../src/inline-thirdparty/simsimd/simsimd/simsimd.h: In function ‘void simsimd_find_metric_punned(simsimd_metric_kind_t, simsimd_datatype_t, simsimd_capability_t, simsimd_capability_t, void (**)(const void*, const void*, simsimd_size_t, simsimd_distance_t*), simsimd_capability_t*)’:
../../src/inline-thirdparty/simsimd/simsimd/simsimd.h:574:78: error: using value of assignment with ‘volatile’-qualified left operand is deprecated [-Werror=volatile]
  574 |             case simsimd_metric_dot_k: *m = (m_t)&simsimd_dot_f64_serial, *c = simsimd_cap_serial_k; return;
      |                                                                           ~~~^~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

Include SimSIMD in a project built with GCC 13

### Expected behavior

Ideally there should be no warnings, because many projects treat warnings as errors.

### SimSIMD version

v5.1.0

### Operating System

AlmaLinux 8

### Hardware architecture

x86

### Which interface are you using?

C implementation

### Contact Details

mbautin@gmail.com

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Hi @mbautin! There is a simple and clean solution that may work: `-Wvolatile`. I'll merge that solution in a bit, but let me know if it doesn't help. There are many way to solve this 🤗
