### ISSUE TITLE
Bug: segfault when calling `simsimd.cdist` without `metric=` keyword argument in Python

### ISSUE THREAD

**Issue by fancidev** [ashvardanian/SimSIMD#194]
### Describe the bug

When calling `simsimd.cdist` passing the metric as a positional argument (instead of a keyword argument), a segfault is raised.

### Steps to reproduce

```python
import simsimd
import numpy as np

u = np.array([[-0.30039746, -0.13594460, 0.58292344]])
v = np.array([[-0.65563949, -0.29700866, 1.27146813]])

# simsimd.cdist(u, v, metric="sqeuclidean")  # ok
simsimd.cdist(u, v, "sqeuclidean")  # seg fault
```

### Expected behavior

No segfault.

It seems to be a problem with how the Python binding is written rather than with the underlying algorithm.

### SimSIMD version

5.4.3

### Operating System

macOS Sonoma

### Hardware architecture

Arm

### Which interface are you using?

Python bindings

### Are you open to being tagged as a contributor?

- [ ] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
That's true, there is a `SEGFAULT`. I've noticed the issue yesterday, when sharing the benchmarks, will look into it. Thanks, @fancidev!
