### ISSUE TITLE
Bug: The One-to-One Distance Python example compares an array value with a scalar value

### ISSUE THREAD

**Issue by yurivict** [ashvardanian/SimSIMD#219]
### Describe the bug

This example from README:
```
from random import randint
import numpy as np
import simsimd as simd

length1, length2 = randint(1, 100), randint(1, 100)
vec1 = np.random.randint(0, 1000, length1).astype(np.uint16)
vec2 = np.random.randint(0, 1000, length2).astype(np.uint16)

slow_result = np.intersect1d(vec1, vec2)
fast_result = simd.intersect(vec1, vec2)
assert slow_result == fast_result
```
compares these 2 values:
```
slow_result=[299 926]
fast_result=0.0
```

### Steps to reproduce

n/a

### Expected behavior

n/a

### SimSIMD version

5.9.6

### Operating System

FreeBSD 14.1

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
You are right, the length of the NumPy result should be taken. Will patch soon. Thanks!
