### ISSUE TITLE
Latest version not on pypi

### ISSUE THREAD

**Issue by guyrosin** [ashvardanian/SimSIMD#42]
Hey @ashvardanian,
I've just found this cool library, started experimenting with it (awesome speedups!) and noticed the latest version on [pypi](https://pypi.org/project/simsimd/#history) is v3.5.5, so just letting you know :)
Thanks for your work!

**Comment by ashvardanian** [comment]
Oh, thanks for noticing! GitHub CI occasionally fails some HTTP request and abrupts the build. https://github.com/ashvardanian/SimSIMD/actions/runs/6992475734 and it worked. The new version is already on PyPI 🤗
