### ISSUE TITLE
Maybe a faster dot product (I'm not sure)

### ISSUE THREAD

**Issue by javiabellan** [ashvardanian/SimSIMD#45]
Looking at [AVX512 dot product](https://github.com/ashvardanian/SimSIMD/blob/main/include/simsimd/spatial.h#L840) I tried to avoid the if inside the loop to make a faster code. Here is a (not tested) idea of the proposed code:

```c
simsimd_avx512_f32_ip(simsimd_f32_t const* a, simsimd_f32_t const* b, simsimd_size_t n)
{
    __m512 ab_vec = _mm512_setzero();
    __m512 a_vec, b_vec;

    int n_tail = n & 15; // Equivalent of n%16 but faster
    n -= n_tail;

    while(n) // faster loop without the "being on the tail condition"
    {
        a_vec = _mm512_loadu_ps(a);
        b_vec = _mm512_loadu_ps(b);
        ab_vec = _mm512_fmadd_ps(a_vec, b_vec, ab_vec);

        a += 16, b += 16, n -= 16;
    }
    if(n_tail)
    {
        __mmask16 mask = _bzhi_u32(0xFFFFFFFF, n_tail);
        a_vec = _mm512_maskz_loadu_ps(mask, a);
        b_vec = _mm512_maskz_loadu_ps(mask, b);
        ab_vec = _mm512_fmadd_ps(a_vec, b_vec, ab_vec);
    }

    return _mm512_reduce_add_ps(ab_vec);
}
````

**Comment by ashvardanian** [comment]
Hi @javiabellan, thanks for the contribution! The `while` is actually identical to a combination of `if` and `goto`, so the performance should be the same.

**Comment by ashvardanian** [comment]
I am not sure the AVX-512 versions have room for improvement, but for Apple one can try to replace NEON with AMX. Let me know if you can test those 🤗

**Comment by javiabellan** [comment]
I see it. I was thinking about the condition in assembly. Maybe cheking if is not zero (JNZ) is faster than n < 16. But i dont really know.
