### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by sroussey** [ashvardanian/SimSIMD#47]
Please add typescript types so my IDE is happy. Thanks!

**Comment by ashvardanian** [comment]
We've previously tried adding TypeScript annotations in other projects, like [USearch](https://github.com/unum-cloud/usearch), but it seriously confuses the documentation generator and messes up the build. Is there a non-intrusive way to achieve that? Maybe by improving the JSDoc in [simsimd.js](https://github.com/ashvardanian/SimSIMD/blob/main/javascript/simsimd.js)?

**Comment by sroussey** [comment]
I’m traveling at the moment, you can [convert jsdoc to typescript descriptor](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).

**Comment by ashvardanian** [comment]
@nairihar, thoughts?
