### ISSUE TITLE
-31 instead of 32?

### ISSUE THREAD

**Issue by sroussey** [ashvardanian/SimSIMD#48]
https://github.com/ashvardanian/SimSIMD/blob/a29f68a0eb08214d5cbdf6bb9e1be3857d27598c/javascript/test/simsimd.test.js#L41

Why is the dot product not 32?

**Comment by ashvardanian** [comment]
@sroussey because that's the inner-product _distance_, not just the inner product. It's computed as $1 - ab$.

**Comment by sroussey** [comment]
Ah, got it! Thx.
