### ISSUE TITLE
main-dev tests main?

### ISSUE THREAD

**Issue by sroussey** [ashvardanian/SimSIMD#54]
I am looking at this line:

https://github.com/ashvardanian/SimSIMD/blob/0aea96c6048a58f63eed5797e028708ae9b5e15d/.github/workflows/prerelease.yml#L72

And it looks like the workflow for main-dev checks out the main branch instead to test.

**Comment by sroussey** [comment]
If it is wrong, I can fix it with some other tweaks I am working on.

**Comment by sroussey** [comment]
Also, you use [checkout@3](https://github.com/ashvardanian/SimSIMD/blob/0aea96c6048a58f63eed5797e028708ae9b5e15d/.github/workflows/prerelease.yml#L30) and [checkout@4](https://github.com/ashvardanian/SimSIMD/blob/0aea96c6048a58f63eed5797e028708ae9b5e15d/.github/workflows/prerelease.yml#L70). Any reason for the different versions?

**Comment by ashvardanian** [comment]
Both are copy-paste issues and should be fixed, thank you, @sroussey!
