### ISSUE TITLE
Jaccard in parallel? simsimd.cdist

### ISSUE THREAD

**Issue by norsedrunkensailor** [ashvardanian/SimSIMD#65]
Will it be possible to extend simsimd.cdist to allow for Jaccard distances to be calculated in batch?

**Comment by ashvardanian** [comment]
It [should](https://github.com/ashvardanian/SimSIMD/blob/9567639f610fa05cd48998a4a78cbc6e4b54086b/python/lib.c#L97) already be supported. If not, can you provide a snippet or maybe extend the [test](https://github.com/ashvardanian/SimSIMD/blob/9567639f610fa05cd48998a4a78cbc6e4b54086b/python/test.py#L158)?

**Comment by norsedrunkensailor** [comment]
Is this correct usage? 
<img width="597" alt="Screenshot 2024-01-22 at 09 55 31" src="https://github.com/ashvardanian/SimSIMD/assets/157128403/ae2b1a7b-1f58-47c8-bafc-424c925bdd3c">

**Comment by ashvardanian** [comment]
That shouldn't work @norsedrunkensailor, as Jaccard distance is a distance between sets, not continuous vectors. In our case, its implemented for bitsets. So you may want to compare values against ones and then call `np.packbits` before passing to SimSIMD. Let me know of that helps 🤗

**Comment by norsedrunkensailor** [comment]
A yes, of course -- sorry. I was trying to implement a method proposed in https://link.springer.com/article/10.1007/s41060-017-0064-z which reduces the number of operations using the related Tanimoto Coeff and some bounding conditions. Using np.packbits works. Is there a way of monitoring progress for large (10**5 by 10**5 batches of all pairs similarity search)? to get any estimate of how long it will take? Thank you again 😁🍀

**Comment by ashvardanian** [comment]
@norsedrunkensailor for progress tracking please check out the USearch library. It adds multithreading and custom logging functionality among other things 🤗
