### ISSUE TITLE
Disabling usage of AVX-512 instructions

### ISSUE THREAD

**Issue by Charlyo** [ashvardanian/SimSIMD#68]
First of all, thank you for this amazing project!

However, in my laptop equiped with and i7 10750h, the AVX512 capability is activated despite the processor not accepting the instruction. Is there any way to disable AVX-512 instructions in python (like a method "set capability").

Thank you for the time and effort.

**Comment by ashvardanian** [comment]
Hi @Charlyo! What's your CPU model? Which language binding are you using?

**Comment by ashvardanian** [comment]
Hi @Charlyo! I've just pushed a patch that should fix your issue. Please let me know how it works 🤗

**Comment by Charlyo** [comment]
Really good news! Thank you very much, @ashvardanian!! Will try once I have some time.
Let me know once you have time to implement the AVX2 implementation as well :)

**Comment by ashvardanian** [comment]
Many functions already have AVX2 acceleration. Any specific ones that you are looking for?

**Comment by Charlyo** [comment]
Basically hamming distance with uint8 type coded binary hash. Would be awesome to have xor + popcount implemented in AVX2.

**Comment by ashvardanian** [comment]
Sure, the #69 is coming later :)
