### ISSUE TITLE
AVX2 popcount implementation

### ISSUE THREAD

**Issue by Charlyo** [ashvardanian/SimSIMD#69]
Right now for x86 it seems there's only serial and AVX-512 popcount hamming implementation.

Could you also implement AVX2 based one? [Can be found  here](https://stackoverflow.com/questions/50081465/counting-1-bits-population-count-on-large-data-using-avx-512-or-avx-2).

Thank you very much.

**Comment by ashvardanian** [comment]
Yes, that can be done. I am a bit overloaded the next week. Any chance you can open a PR for this?

Looking at the replies in the thread, Wojciech's variant looks great. We just need to adjust the style, remove loop unrolling, and add references to the original.

**Comment by Charlyo** [comment]
I'm not profient at C or C++. Would rather let someone more experienced to do the job (if that's ok).

**Comment by jianshu93** [comment]
Hello Both,

I believe libpopcnt.h has all AVX implementations of popcount: https://github.com/kimwalisch/libpopcnt

There is not need to implement an additional one.  However, I think include it into this library can be useful.

Jianshu

**Comment by ashvardanian** [comment]
It's a good idea to add popcount, and `libpopcnt` looks nice, but we only need one routine for AVX2 Harley Seal transform. Would be easier to add those few lines of C code, than to add the first dependency update all of CI. Coincidently, [ClickHouse](https://github.com/ClickHouse/ClickHouse/issues/59389#issue-2108346845) and other users have expressed interest in bit-level operations, so I'm definitely open to PRs 🤗
