### ISSUE TITLE
Golang: '_Float16' is not supported on this target

### ISSUE THREAD

**Issue by corani** [ashvardanian/SimSIMD#71]
After fixing the a few issues (#70) I'm getting the following error:

```
$ go test
# github.com/ashvardanian/simsimd/golang
In file included from ./../include/simsimd/binary.h:23,
                 from ./../include/simsimd/simsimd.h:21,
                 from ./simsimd.go:6:
./../include/simsimd/types.h:119:9: error: '_Float16' is not supported on this target
  119 | typedef _Float16 simsimd_f16_t;
      |         ^~~~~~~~
FAIL    github.com/ashvardanian/simsimd/golang [build failed]
```

**Comment by corani** [comment]
I've temporarily hacked around it by setting `SIMSIMD_NATIVE_F16 0` in https://github.com/ashvardanian/SimSIMD/blob/main/include/simsimd/types.h#L120, but obviously that isn't the right solution. With that (and the changes in #70) it seems to work though.

**Comment by ashvardanian** [comment]
@corani, thank you for the issue and the PR 🤗 
That one is patched, and this will be fixed with the next release.

**Comment by corani** [comment]
@ashvardanian your change works, but I'm wondering if the problem isn't in the type support detection. Maybe it's just something on my system?
