### ISSUE TITLE
Expose binary distances and divergence functions in Rust

### ISSUE THREAD

**Issue by ashvardanian** [ashvardanian/SimSIMD#84]
At this point the Rust binding exposes only 3 of 7 accelerated distance functions.
What's remaining:

- Hamming,
- Jaccard,
- Kullback-Leibler divergence,
- Jensen-Shannon divergence.

**Comment by pplanel** [comment]
i would like to work on this!

**Comment by ashvardanian** [comment]
Hi @pplanel! I plan to work on this tomorrow. Let me know if you have any patches you want to submit 🤗
