### ISSUE TITLE
Can't install on institutional linux cluster

### ISSUE THREAD

**Issue by alexanderchang1** [ashvardanian/SimSIMD#86]
Hi,

`pip install simsimd` can only get up to version 1.4.0 due to wheel/manylinux incompatibility with my OS, do you have any advice on how I could install later versions? 'sim'simd' is a dependence in another package I'm using.

`NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"`

**Comment by ashvardanian** [comment]
This is related on #72. Can be fixed by bringing the upgraded CI from StringZilla project to SimSIMD. I can look at it in the next few days. Feel free to suggest a patch in the meantime 🤗

**Comment by alexanderchang1** [comment]
Hi, I added a build_wheels.yml in an attempt to fix it in #87 . Apologies for any mistakes, not familiar with git workflows.

**Comment by ashvardanian** [comment]
@alexanderchang1 the new release is out, please let me know if it solves you issue 🤗

**Comment by alexanderchang1** [comment]
Hi, 

Sorry, it's still not working, I looked in the build wheel action and for some reason it's skipping manylinux2014 for the x86_64 architecture. I couldn't figure out why. 

simsimd-3.8.1-cp310-cp310-manylinux_2_17_s390x.manylinux2014_s390x.whl (125.1 kB [view hashes](https://pypi.org/project/simsimd/#copy-hash-modal-c2323507-b85f-49dc-b47a-606be7860255))

Uploaded about 6 hours ago cp310
simsimd-3.8.1-cp310-cp310-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl (151.4 kB [view hashes](https://pypi.org/project/simsimd/#copy-hash-modal-80234b4e-29e9-43f1-b5da-046b0a798d17))

Uploaded about 6 hours ago cp310
simsimd-3.8.1-cp310-cp310-manylinux_2_17_i686.manylinux2014_i686.whl (127.1 kB [view hashes](https://pypi.org/project/simsimd/#copy-hash-modal-1c95d349-588b-401d-bbbb-944554e7deb2))

Uploaded about 6 hours ago cp310

These are the system tags my system has permitted

cp310-cp310-manylinux_2_17_x86_64
cp310-cp310-manylinux2014_x86_64
cp310-cp310-manylinux_2_16_x86_64
cp310-cp310-manylinux_2_15_x86_64
cp310-cp310-manylinux_2_14_x86_64
cp310-cp310-manylinux_2_13_x86_64
cp310-cp310-manylinux_2_12_x86_64
cp310-cp310-manylinux2010_x86_64
cp310-cp310-manylinux_2_11_x86_64
cp310-cp310-manylinux_2_10_x86_64
cp310-cp310-manylinux_2_9_x86_64
cp310-cp310-manylinux_2_8_x86_64
cp310-cp310-manylinux_2_7_x86_64
cp310-cp310-manylinux_2_6_x86_64
cp310-cp310-manylinux_2_5_x86_64
cp310-cp310-manylinux1_x86_64
cp310-cp310-linux_x86_64
cp310-abi3-manylinux_2_17_x86_64
cp310-abi3-manylinux2014_x86_64
cp310-abi3-manylinux_2_16_x86_64
cp310-abi3-manylinux_2_15_x86_64
cp310-abi3-manylinux_2_14_x86_64
cp310-abi3-manylinux_2_13_x86_64
cp310-abi3-manylinux_2_12_x86_64
cp310-abi3-manylinux2010_x86_64
cp310-abi3-manylinux_2_11_x86_64
cp310-abi3-manylinux_2_10_x86_64
cp310-abi3-manylinux_2_9_x86_64
cp310-abi3-manylinux_2_8_x86_64
cp310-abi3-manylinux_2_7_x86_64
cp310-abi3-manylinux_2_6_x86_64
cp310-abi3-manylinux_2_5_x86_64
cp310-abi3-manylinux1_x86_64
cp310-abi3-linux_x86_64
cp310-none-manylinux_2_17_x86_64
cp310-none-manylinux2014_x86_64
cp310-none-manylinux_2_16_x86_64
cp310-none-manylinux_2_15_x86_64
cp310-none-manylinux_2_14_x86_64
cp310-none-manylinux_2_13_x86_64
cp310-none-manylinux_2_12_x86_64
cp310-none-manylinux2010_x86_64
cp310-none-manylinux_2_11_x86_64
cp310-none-manylinux_2_10_x86_64
cp310-none-manylinux_2_9_x86_64
cp310-none-manylinux_2_8_x86_64
cp310-none-manylinux_2_7_x86_64
cp310-none-manylinux_2_6_x86_64
cp310-none-manylinux_2_5_x86_64
cp310-none-manylinux1_x86_64
cp310-none-linux_x86_64

**Comment by alexanderchang1** [comment]
Hi just wanted to bump this @ashvardanian
