### ISSUE TITLE
I want to add the simsimd to xmake's package management tool and have encountered some error.

### ISSUE THREAD

**Issue by Seedking** [ashvardanian/SimSIMD#99]
[xmake-repo simsimd pr](https://github.com/xmake-io/xmake-repo/pull/3409)
There are some error with the simsimd package during the testing and compilation phase.  
I don't understand SIMD-related knowledge very well.
How should I resolve these errors?

iphoneos | android v8a r22： 
```
simsimd/spatial.h:350:16: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
        ab_vec = vdotq_s32(ab_vec, a_vec, b_vec);
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/.xmake/packages/s/simsimd/v3.9.0/181e36b5210a41de9a550584e58f8699/include/simsimd/spatial.h:351:16: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
        a2_vec = vdotq_s32(a2_vec, a_vec, a_vec);
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/runner/.xmake/packages/s/simsimd/v3.9.0/181e36b5210a41de9a550584e58f8699/include/simsimd/spatial.h:352:16: error: assigning to 'int32x4_t' (vector of 4 'int32_t' values) from incompatible type 'int'
        b2_vec = vdotq_s32(b2_vec, b_vec, b_vec);
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

ubuntu:
```
simsimd/types.h:122:9: error: ‘_Float16’ is not supported on this target
  122 | typedef _Float16 simsimd_f16_t;
      |         ^~~~~~~~
```

**Comment by ashvardanian** [comment]
Hi @Seedking! Thanks for your effort! It would great to have SimSIMD in xmake!

The 2 issues your are seeing are unrelated to each other.

---

For the second issue, there are a couple of ways to fix it. Either avoid native `f16` support entirely, by overriding `SIMSIMD_NATIVE_F16=0`. The second option would be to find a better way to infer native `f16` support here: 

https://github.com/ashvardanian/SimSIMD/blob/3e51bacb1b74a7ed3fa7bb037162276047192bab/include/simsimd/types.h#L167-L194

It would be amazing if you could submit a patch for the `f16` resolution here. It would help me a lot, and will be immediately used in USearch and several databases.

---

For the first issue, I suspect something is wrong with the following Clang/GCC `__attribute__`:

https://github.com/ashvardanian/SimSIMD/blob/3e51bacb1b74a7ed3fa7bb037162276047192bab/include/simsimd/spatial.h#L303-L305

It works fine in my pipelines, so can you please share the hardware you are running on and the compiler version.

**Comment by waruqi** [comment]
I have added it to xmake-repo. https://github.com/xmake-io/xmake-repo/pull/3409

**Comment by Seedking** [comment]
thank you answer! i will try to add all your repo to xmake
